/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as ScanHistoryIndexRouteImport } from './routes/scan-history/index'
import { Route as NetworksIndexRouteImport } from './routes/networks/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ContainersContainerIdLogsRouteImport } from './routes/containers/$containerId/logs'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanHistoryIndexRoute = ScanHistoryIndexRouteImport.update({
  id: '/scan-history/',
  path: '/scan-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksIndexRoute = NetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdLogsRoute =
  ContainersContainerIdLogsRouteImport.update({
    id: '/containers/$containerId/logs',
    path: '/containers/$containerId/logs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/scan-history/': typeof ScanHistoryIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts': typeof AlertsIndexRoute
  '/images': typeof ImagesIndexRoute
  '/networks': typeof NetworksIndexRoute
  '/scan-history': typeof ScanHistoryIndexRoute
  '/stats': typeof StatsIndexRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/alerts/': typeof AlertsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/networks/': typeof NetworksIndexRoute
  '/scan-history/': typeof ScanHistoryIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/containers/$containerId/logs': typeof ContainersContainerIdLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/demo/tanstack-query'
    | '/alerts/'
    | '/images/'
    | '/networks/'
    | '/scan-history/'
    | '/stats/'
    | '/containers/$containerId/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/demo/tanstack-query'
    | '/alerts'
    | '/images'
    | '/networks'
    | '/scan-history'
    | '/stats'
    | '/containers/$containerId/logs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/demo/tanstack-query'
    | '/alerts/'
    | '/images/'
    | '/networks/'
    | '/scan-history/'
    | '/stats/'
    | '/containers/$containerId/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  NetworksIndexRoute: typeof NetworksIndexRoute
  ScanHistoryIndexRoute: typeof ScanHistoryIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  ContainersContainerIdLogsRoute: typeof ContainersContainerIdLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-history/': {
      id: '/scan-history/'
      path: '/scan-history'
      fullPath: '/scan-history/'
      preLoaderRoute: typeof ScanHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks/': {
      id: '/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof NetworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId/logs': {
      id: '/containers/$containerId/logs'
      path: '/containers/$containerId/logs'
      fullPath: '/containers/$containerId/logs'
      preLoaderRoute: typeof ContainersContainerIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  NetworksIndexRoute: NetworksIndexRoute,
  ScanHistoryIndexRoute: ScanHistoryIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  ContainersContainerIdLogsRoute: ContainersContainerIdLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
